'use client';
import { useEffect, useState } from 'react'; import ProductCard from '@/components/ProductCard'; import Link from 'next/link';
type Product = { id: string; slug: string; name: string; brand: string; mrp: number; basePrice: number; variants: { image: string }[]; emiPlans: { monthlyPayment: number }[] };
export default function Home() {
    const [data, setData] = useState<Product[]>([]), [loading, setLoading] = useState(true), [err, setErr] = useState(false), [search, setSearch] = useState(''), [brand, setBrand] = useState('All'), [sort, setSort] = useState('newest'), [compare, setCompare] = useState<string[]>([]);
    const load = () => { setLoading(true); setErr(false); const q = new URLSearchParams(); if (search) q.set('search', search); if (brand !== 'All') q.set('brand', brand); q.set('sort', sort); fetch(`/api/products?${q}`).then(r => r.ok ? r.json() : Promise.reject()).then(x => setData(x.data || [])).catch(() => setErr(true)).finally(() => setLoading(false)) };
    useEffect(() => { const t = setTimeout(load, 250); return () => clearTimeout(t) }, [search, brand, sort]);
    const brands = ['All', ...Array.from(new Set(data.map(p => p.brand)))];
    return <main className="wrap"><section className="hero"><div><div className="eyebrow">Smart EMI marketplace</div><h1>Own the tech you want.<br /><span>Pay your way.</span></h1><p>Compare flagship smartphones, choose a variant and get a transparent EMI plan backed by trusted mutual-fund financing and a secure digital application flow.</p><div className="hero-actions"><Link className="proceed hero-btn" href="#products">Explore products</Link><Link className="outline-btn hero-btn" href="/emi-calculator">Calculate EMI</Link></div></div><div className="hero-art"><div className="hero-phone">📱</div><div className="hero-chip">Low interest<br /><strong>Flexible EMI</strong></div></div></section><section id="products" className="toolbar"><div><h2>Popular smartphones</h2><p>Live catalog from PostgreSQL</p></div><div className="filters"><input aria-label="Search products" placeholder="Search brand or product…" value={search} onChange={e => setSearch(e.target.value)} /><select value={brand} onChange={e => setBrand(e.target.value)}>{brands.map(b => <option key={b}>{b}</option>)}</select><select value={sort} onChange={e => setSort(e.target.value)}><option value="newest">Newest</option><option value="price_asc">Price: low to high</option><option value="price_desc">Price: high to low</option></select></div></section>{compare.length > 0 && <div className="compare-bar"><span><strong>{compare.length}</strong> product{compare.length > 1 ? 's' : ''} selected</span><Link className="proceed small-btn" href={`/compare?ids=${compare.join(',')}`}>Compare now</Link><button className="text-btn" onClick={() => setCompare([])}>Clear</button></div>}{loading ? <div className="skeleton-grid">{[1, 2, 3].map(i => <div className="skeleton" key={i} />)}</div> : err ? <div className="error">Unable to load products. Please try again. <button onClick={load}>Retry</button></div> : data.length === 0 ? <div className="empty">No products available.<button onClick={() => { setSearch(''); setBrand('All') }}>Clear filters</button></div> : <section className="grid">{data.map(p => <ProductCard key={p.id} p={p} selected={compare.includes(p.id)} onCompare={() => setCompare(x => x.includes(p.id) ? x.filter(id => id !== p.id) : x.length < 3 ? [...x, p.id] : x)} />)}</section>}<section className="trust"><div><b>0 Down Payment</b><small>Flexible options</small></div><div><b>Quick Approval</b><small>Digital application</small></div><div><b>Secure KYC</b><small>Masked identity data</small></div><div><b>Smart Recommendation</b><small>Plan insights</small></div></section></main>
}
